version: '3.7'

services:
  node-app:
    name: nodeapp
    image: node-app:v3.0
    ports:
      - 8092:8000
    volumes:
      - node-app-data:/app/storage
    restart: always

volumes:
  node-app-data:
